CREATE TABLE IF NOT EXISTS Role (
  RoleID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  RoleName VARCHAR(80) NOT NULL,
  Description TEXT,
  PRIMARY KEY (RoleID)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;
