CREATE TABLE IF NOT EXISTS User (
  UserID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  UserName VARCHAR(80) NOT NULL,
  UserPassword VARCHAR(80) NOT NULL,
  UserEmail VARCHAR(80),
  IsActive TINYINT DEFAULT 1,
  CanLogin TINYINT DEFAULT 1,
  RoleID INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (UserID),
  FOREIGN KEY (RoleID) REFERENCES Role(RoleID)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;
